[workspace]
changelog_update = true       # disable changelog updates
dependencies_update = true    # update dependencies with `cargo update`
pr_branch_prefix = "release-" # PR branch prefix
publish_timeout = "10m"       # set a timeout for `cargo publish`

[[package]]
name = "arenabuddy"
publish = false
release = false
git_release_enable = false

[[package]]
name = "arenabuddy_core"
publish = true
git_release_enable = false

[[package]]
name = "arenabuddy_cli"
publish = true
git_release_enable = false

[[package]]
name = "arenabuddy_scraper"
publish = false
release = false
git_release_enable = false

[[package]]
name = "arenabuddy_ui"
publish = false
release = false
git_release_enable = false
